import Footer from "@/components/Footer";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";
import { NavbarProvider } from "@/contexts/AppContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body>
        <NavbarProvider>
          {<NavigationBar />}
          {/* {<Header />} */}
          {children}
          {<Footer />}
        </NavbarProvider>
      </body>
    </html>
  );
}
