import "./globals.css";
import NavigationBar from "@/components/NavigationBar";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  
  return (
    <html lang="en">
      <body
      >
        {<NavigationBar />}
        {<Header pageKey={"how_timeline"} />}
        {children}
      </body>
    </html>
  );
}
